# Generated by Django 5.0.7 on 2024-07-28 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='behavior_and_social_skills',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interests_and_extracurricular',
        ),
        migrations.RemoveField(
            model_name='student',
            name='motivation_and_engagement',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='student',
            name='behavior',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='engagement_levels',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='social_skills',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_sheet',
            field=models.FileField(upload_to='grades/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='special_needs',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='unhealthy_habits',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentApp.class'),
            preserve_default=False,
        ),
    ]
