# Generated by Django 5.0.7 on 2024-07-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_class_remove_student_behavior_and_social_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade_sheet',
            field=models.FileField(blank=True, null=True, upload_to='grades/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
