# Generated by Django 5.0.7 on 2024-07-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0004_subject_studentsubject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('can_assign_subjects', 'Can assign subjects to students')]},
        ),
    ]
