# Generated by Django 5.0.7 on 2024-07-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0005_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
